ROC-3374 template change to remove heading
hmcts/cmc-common-frontend pull request #102
Opened 2018-04-27 12:06 UTC by rattur

Update template to remove heading and subsequently allow a11y tests to run successfully for story

https://tools.hmcts.net/jira/browse/ROC-3374

2018-04-27 12:44 UTC, DamianDunajski requested changes

2018-04-27 12:44 UTC, geek-soft commented on macros/remainingTasksFragment.njk
>  {% macro remainingTasksFragment(heading, tasks, backLink) %}
Remove unused arg.

2018-04-27 12:46 UTC, rattur commented on macros/remainingTasksFragment.njk
>  {% macro remainingTasksFragment(heading, tasks, backLink) %}
Oh of course

2018-04-27 14:13 UTC, robertparkinson approved these changes

2018-04-30 09:33 UTC, DamianDunajski approved these changes

2018-04-30 09:42 UTC, merged